// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spnkwyczvkemfiofuiqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwbmt3eWN6dmtlbWZpb2Z1aXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTE3NDQsImV4cCI6MjA3MjA2Nzc0NH0.Ub-lVLjx-jtomJ2xK0Mg29fHitcVT9GVbeTMiCTTbaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});